version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 1000:80
    volumes:
      - git:/usr/share/nginx/html
    command: mkdir -p /usr/share/nginx/html
    build:
      context: .
      dockerfile: Dockerfile
