version: '3.8'

services:
  webserver:
    image: nginx:latest
    ports:
      - "2000:80"
    volumes:
      - mein-webverzeichnis:/usr/share/nginx/html

volumes:
  mein-webverzeichnis:
    driver: local
