version: '3'

services:
  git-clone:
    image: alpine/git
    volumes:
      - my-volume:/app
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "if [ -d /app ]; then
        rm -rf /app/*
      fi &&
      apk update &&
      apk add --no-cache git &&
      git clone https://github.com/mxmueller/home-build-service.git /app"

volumes:
  my-volume:
