version: '3'
services:
  git-clone:
    build:
      context: .
      dockerfile: Dockerfile.git
    volumes:
      - nginx-data:/usr/share/nginx/html
    depends_on:
      - nginx

  nginx:
    image: nginx
    ports:
      - 1000:80
    volumes:
      - nginx-data:/usr/share/nginx/html

volumes:
  nginx-data:
