version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 1000:80
    volumes:
      - git:/app/data
    command: mkdir -p /app/data
    build:
      context: .
      dockerfile: Dockerfile
