version: '3'

services:
  frontend-prod:
    image: nginx
    volumes:
      - source_data:/usr/share/nginx/html
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  source_data:
    external: true
