version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "2000:80"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/usr/share/nginx/html
      
volumes:
  data:
